repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

helmDefaults:
  #kubeContext: dev.ibi.local
  cleanupOnFail: true
  wait: false
  timeout: 300
  #recreatePods: true
  force: false
  historyMax: 10
  createNamespace: true

releases:
  - name: postgres
    chart: ../../charts/postgresql
    version: 12.11.1
    namespace: ikawari
    createNamespace: true
    wait: true


  - name: indexer-mongodb
    chart: ../../charts/mongodb
    version: 13.18.1
    namespace: ikawari
    createNamespace: true
    wait: true
    values:
      - podAnnotations: {
        "cni.projectcalico.org/ipAddrs": "[\"10.1.156.84\"]"
      }
      - ../common/values-mongodb.yaml
