## See https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
image:
  tag: "4.4.15-debian-10-r8"
usePassword: false
serviceAccount:
  create: true
resources:
  requests:
    cpu: "1"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "2Gi"