apiVersion: v1
kind: Service
metadata:
  name: {{ include "ikawarinode.fullname" . }}
  labels:
    {{- include "ikawarinode.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{ range $key, $value := .Values.node.ports }}
    - port: {{$value.containerPort}}
      name: {{$value.name}}
      targetPort: {{$value.containerPort}}
      protocol: {{$value.protocol}}
    {{ end }}
  selector:
    {{- include "ikawarinode.selectorLabels" . | nindent 4 }}
